services:
  mysql:
    image: mysql:9.2.0
    container_name: mysql_compose
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: nowtrip
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
#      - ./mysql_init:/docker-entrypoint-initdb.d

  redis:
    image: redis:alpine
    container_name: redis_compose
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  springboot:
    build: .
    container_name: springboot_compose
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/nowtrip
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

volumes:
  mysql_data:
  redis_data: