-- 통화 정보
INSERT INTO currency (id, code, name, symbol, korean_name, currency_flag_code) VALUES
(1, 'AUD', 'Australian Dollar', 'A$', '호주 달러', 'au'),
(2, 'EUR', 'Euro', '€', '유로', 'eu'),  -- 유럽 공통 코드 사용
(3, 'BRL', 'Brazilian Real', 'R$', '브라질 레알', 'br'),
(4, 'CAD', 'Canadian Dollar', 'C$', '캐나다 달러', 'ca'),
(5, 'CNY', 'Chinese Yuan', '¥', '중국 위안', 'cn'),
(6, 'EGP', 'Egyptian Pound', 'E£', '이집트 파운드', 'eg'),
(7, 'USD', 'US Dollar', '$', '미국 달러', 'us'),  -- 미국 달러 공통 코드 사용
(8, 'HKD', 'Hong Kong Dollar', 'HK$', '홍콩 달러', 'hk'),
(9, 'IDR', 'Indonesian Rupiah', 'Rp', '인도네시아 루피아', 'id'),
(10, 'JPY', 'Japanese Yen', '¥', '일본 엔', 'jp'),
(11, 'MYR', 'Malaysian Ringgit', 'RM', '말레이시아 링깃', 'my'),
(12, 'MXN', 'Mexican Peso', 'Mex$', '멕시코 페소', 'mx'),
(13, 'MAD', 'Moroccan Dirham', 'MAD', '모로코 디르함', 'ma'),
(14, 'NZD', 'New Zealand Dollar', 'NZ$', '뉴질랜드 달러', 'nz'),
(15, 'PHP', 'Philippine Peso', '₱', '필리핀 페소', 'ph'),
(16, 'SGD', 'Singapore Dollar', 'S$', '싱가포르 달러', 'sg'),
(17, 'ZAR', 'South African Rand', 'R', '남아프리카 랜드', 'za'),
(18, 'KRW', 'South Korean Won', '₩', '대한민국 원', 'kr'),
(19, 'CHF', 'Swiss Franc', 'CHF', '스위스 프랑', 'ch'),
(20, 'TWD', 'New Taiwan Dollar', 'NT$', '대만 달러', 'tw'),
(21, 'THB', 'Thai Baht', '฿', '태국 바트', 'th'),
(22, 'TRY', 'Turkish Lira', '₺', '터키 리라', 'tr'),
(23, 'AED', 'UAE Dirham', 'د.إ', '아랍에미리트 디르함', 'ae'),
(24, 'GBP', 'British Pound', '£', '영국 파운드', 'gb'),
(25, 'VND', 'Vietnamese Dong', '₫', '베트남 동', 'vn');

-- 나라 정보
INSERT INTO country (id, name, korean_name, iso2code, iso3code, currency_id) VALUES
(1, 'Australia', '호주', 'AU', 'AUS', 1),
(2, 'Austria', '오스트리아', 'AT', 'AUT', 2),
(3, 'Brazil', '브라질', 'BR', 'BRA', 3),
(4, 'Canada', '캐나다', 'CA', 'CAN', 4),
(5, 'China', '중국', 'CN', 'CHN', 5),
(6, 'Czechia', '체코', 'CZ', 'CZE', 2),
(7, 'Egypt', '이집트', 'EG', 'EGY', 6),
(8, 'France', '프랑스', 'FR', 'FRA', 2),
(9, 'Germany', '독일', 'DE', 'DEU', 2),
(10, 'Greece', '그리스', 'GR', 'GRC', 2),
(11, 'Guam', '괌', 'GU', 'GUM', 7),
(12, 'Hong Kong', '홍콩', 'HK', 'HKG', 8),
(13, 'Indonesia', '인도네시아', 'IN', 'IDN', 9),
(14, 'Italy', '이탈리아', 'IT', 'ITA', 2),
(15, 'Japan', '일본', 'JP', 'JPN', 10),
(16, 'Malaysia', '말레이시아', 'MY', 'MYS', 11),
(17, 'Mexico', '멕시코', 'MX', 'MEX', 12),
(18, 'Morocco', '모로코', 'MA', 'MAR', 13),
(19, 'New Zealand', '뉴질랜드', 'NZ', 'NZL', 14),
(20, 'Philippines', '필리핀', 'PH', 'PHL', 15),
(21, 'Singapore', '싱가포르', 'SG', 'SGP', 16),
(22, 'South Africa', '남아프리카공화국', 'ZA', 'ZAF', 17),
(23, 'South Korea', '대한민국', 'KR', 'KOR', 18),
(24, 'Spain', '스페인', 'ES', 'ESP', 2),
(25, 'Switzerland', '스위스', 'CH', 'CHE', 19),
(26, 'Taiwan', '대만', 'TW', 'TWN', 20),
(27, 'Thailand', '태국', 'TH', 'THA', 21),
(28, 'Turkey', '터키', 'TR', 'TUR', 22),
(29, 'United Arab Emirates', '아랍에미리트', 'AE', 'ARE', 23),
(30, 'United Kingdom', '영국', 'GB', 'GBR', 24),
(31, 'United States', '미국', 'US', 'USA', 7),
(32, 'Vietnam', '베트남', 'VN', 'VNM', 25);